Fix TC7 and add PCxx pins for SAMR.
adafruit/samd-peripherals pull request #2
Opened 2018-08-07 21:40 UTC by tannewt

2018-08-07 21:57 UTC, dhalbert requested changes
Looks good! Just explicate the comment if it makes sense.

2018-08-07 21:57 UTC, dhalbert commented on samd/samd21/pins.c
> +// For SAMR. They have one function so its hardcoded elsewhere.
Do you mean they talk to the radio?

2018-08-08 18:06 UTC, tannewt commented
Ok. I elaborated in the comment.

2018-08-08 18:50 UTC, dhalbert approved these changes
Great! Thanks!

2018-08-08 18:50 UTC, merged